[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
