[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps --no-audit --no-fund && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
