[build]
  base = "frontend"
  # We skip Netlify's install phase and do our own with npm here:
  command = "npm ci || npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NETLIFY_SKIP_INSTALL = "true"  # <-- this is the key
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
